-- liquibase formatted sql

-- changeset Stanley:02010501 labels:v2.1.0
CREATE TABLE constituencies_constituency (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(45) NOT NULL, `description` MEDIUMTEXT NOT NULL, hospitals INT DEFAULT 0 NOT NULL, ambulances INT DEFAULT 0 NOT NULL, death_hazards INT DEFAULT 0 NOT NULL, schools INT DEFAULT 0 NOT NULL, bookshops INT DEFAULT 0 NOT NULL, libraries INT DEFAULT 0 NOT NULL, fallout_shelters INT DEFAULT 0 NOT NULL, railways INT DEFAULT 0 NOT NULL, subway_stations INT DEFAULT 0 NOT NULL, bus_routes INT DEFAULT 0 NOT NULL, airports INT DEFAULT 0 NOT NULL, bears INT DEFAULT 0 NOT NULL, ladders INT DEFAULT 0 NOT NULL, lighthouses INT DEFAULT 0 NOT NULL, residential INT DEFAULT 0 NOT NULL, officespace INT DEFAULT 0 NOT NULL, cell_towers INT DEFAULT 0 NOT NULL, power_stations INT DEFAULT 0 NOT NULL, sewers INT DEFAULT 0 NOT NULL, museums INT DEFAULT 0 NOT NULL, galleries INT DEFAULT 0 NOT NULL, parks INT DEFAULT 0 NOT NULL, nuclear_plants INT DEFAULT 0 NOT NULL, wind_farms INT DEFAULT 0 NOT NULL, clocks INT DEFAULT 0 NOT NULL, pigeons INT DEFAULT 0 NOT NULL, farms INT DEFAULT 0 NOT NULL, cows INT DEFAULT 0 NOT NULL, rainfall INT DEFAULT 0 NOT NULL, fighter_jets INT DEFAULT 0 NOT NULL, tax_rate INT DEFAULT 20 NOT NULL, CONSTRAINT PK_CONSTITUENCIES_CONSTITUENCY PRIMARY KEY (id), UNIQUE (id), UNIQUE (name));

-- changeset Stanley:02010502 labels:v2.1.0
INSERT INTO constituencies_constituency (id, name, `description`, hospitals, ambulances, death_hazards, schools, bookshops, libraries, fallout_shelters, railways, subway_stations, bus_routes, airports, bears, ladders, lighthouses, residential, officespace, cell_towers, power_stations, sewers, museums, galleries, parks, nuclear_plants, wind_farms, clocks, pigeons, farms, cows, rainfall, fighter_jets, tax_rate) VALUES (1, 'Beddingshire', 'Pillow exports are the highest from this constituency.', 2, 3, 2, 9, 16, 7, 5, 2, 0, 22, 3, 24, 42, 12, 240, 30, 43, 68, 13, 16, 3, 5, 52, 12, 374, 132, 29, 197, 4, 4, 20);
INSERT INTO constituencies_constituency (id, name, `description`, hospitals, ambulances, death_hazards, schools, bookshops, libraries, fallout_shelters, railways, subway_stations, bus_routes, airports, bears, ladders, lighthouses, residential, officespace, cell_towers, power_stations, sewers, museums, galleries, parks, nuclear_plants, wind_farms, clocks, pigeons, farms, cows, rainfall, fighter_jets, tax_rate) VALUES (2, 'Dog Shire', 'Dogs are a man''s best friend, and Dog Shire is known for the best dogs.', 5, 9, 2, 9, 18, 1, 8, 7, 2, 22, 0, 38, 44, 6, 213, 40, 34, 43, 36, 9, 9, 0, 45, 18, 212, 91, 27, 200, 15, 1, 20);
INSERT INTO constituencies_constituency (id, name, `description`, hospitals, ambulances, death_hazards, schools, bookshops, libraries, fallout_shelters, railways, subway_stations, bus_routes, airports, bears, ladders, lighthouses, residential, officespace, cell_towers, power_stations, sewers, museums, galleries, parks, nuclear_plants, wind_farms, clocks, pigeons, farms, cows, rainfall, fighter_jets, tax_rate) VALUES (3, 'Crystal', 'Once made masses of money from its Emerald Mines, but they''ve since dried up.', 6, 4, 5, 4, 15, 4, 6, 12, 8, 22, 12, 25, 45, 2, 245, 41, 46, 25, 34, 8, 9, 15, 48, 12, 93, 94, 23, 224, 63, 3, 20);
INSERT INTO constituencies_constituency (id, name, `description`, hospitals, ambulances, death_hazards, schools, bookshops, libraries, fallout_shelters, railways, subway_stations, bus_routes, airports, bears, ladders, lighthouses, residential, officespace, cell_towers, power_stations, sewers, museums, galleries, parks, nuclear_plants, wind_farms, clocks, pigeons, farms, cows, rainfall, fighter_jets, tax_rate) VALUES (4, 'Lumbridgeshire', 'First point of call after Tutorial Island.', 6, 14, 1, 14, 10, 2, 1, 1, 15, 29, 4, 26, 18, 8, 266, 55, 21, 36, 23, 6, 3, 15, 35, 30, 111, 254, 22, 155, 9, 3, 20);
INSERT INTO constituencies_constituency (id, name, `description`, hospitals, ambulances, death_hazards, schools, bookshops, libraries, fallout_shelters, railways, subway_stations, bus_routes, airports, bears, ladders, lighthouses, residential, officespace, cell_towers, power_stations, sewers, museums, galleries, parks, nuclear_plants, wind_farms, clocks, pigeons, farms, cows, rainfall, fighter_jets, tax_rate) VALUES (5, 'City of Kalbal', 'The capital city until someplace else decides to take over.', 4, 12, 5, 2, 9, 4, 4, 2, 14, 19, 13, 18, 29, 4, 234, 50, 17, 16, 48, 13, 6, 21, 40, 21, 429, 10, 32, 137, 28, 6, 20);
INSERT INTO constituencies_constituency (id, name, `description`, hospitals, ambulances, death_hazards, schools, bookshops, libraries, fallout_shelters, railways, subway_stations, bus_routes, airports, bears, ladders, lighthouses, residential, officespace, cell_towers, power_stations, sewers, museums, galleries, parks, nuclear_plants, wind_farms, clocks, pigeons, farms, cows, rainfall, fighter_jets, tax_rate) VALUES (6, 'Maizemaze', 'Lover of corn and corn-related products.', 5, 9, 8, 7, 6, 6, 9, 3, 0, 21, 2, 35, 19, 2, 224, 30, 19, 12, 19, 5, 3, 30, 62, 17, 90, 51, 43, 233, 33, 3, 20);
INSERT INTO constituencies_constituency (id, name, `description`, hospitals, ambulances, death_hazards, schools, bookshops, libraries, fallout_shelters, railways, subway_stations, bus_routes, airports, bears, ladders, lighthouses, residential, officespace, cell_towers, power_stations, sewers, museums, galleries, parks, nuclear_plants, wind_farms, clocks, pigeons, farms, cows, rainfall, fighter_jets, tax_rate) VALUES (7, 'Bumcry', 'They say it''s pronounced BEM-cree but we all know it''s not.', 19, 6, 5, 4, 18, 6, 7, 7, 0, 6, 3, 24, 34, 3, 235, 45, 17, 14, 19, 12, 3, 10, 1, 2, 282, 82, 31, 98, 62, 10, 20);
INSERT INTO constituencies_constituency (id, name, `description`, hospitals, ambulances, death_hazards, schools, bookshops, libraries, fallout_shelters, railways, subway_stations, bus_routes, airports, bears, ladders, lighthouses, residential, officespace, cell_towers, power_stations, sewers, museums, galleries, parks, nuclear_plants, wind_farms, clocks, pigeons, farms, cows, rainfall, fighter_jets, tax_rate) VALUES (8, 'Scone', 'Hundreds of years of historical arguments over its pronounciation.', 23, 14, 1, 0, 13, 2, 5, 4, 0, 9, 2, 29, 26, 5, 235, 50, 13, 18, 37, 5, 20, 3, 54, 33, 417, 142, 30, 84, 63, 6, 20);
INSERT INTO constituencies_constituency (id, name, `description`, hospitals, ambulances, death_hazards, schools, bookshops, libraries, fallout_shelters, railways, subway_stations, bus_routes, airports, bears, ladders, lighthouses, residential, officespace, cell_towers, power_stations, sewers, museums, galleries, parks, nuclear_plants, wind_farms, clocks, pigeons, farms, cows, rainfall, fighter_jets, tax_rate) VALUES (9, 'Gerham', 'A blessed and holy land, dedicated to the arts of the long lost St Gerham, it remains a place that sees its fair share of light, rain, and snow. Old buildings litter the landscape and you won''t be able to escape those age old teachings of the Greater Bovine. The people are accepting, but expect a few door visits.', 3, 9, 1, 8, 32, 4, 1, 3, 0, 7, 4, 31, 27, 5, 229, 40, 9, 7, 21, 10, 5, 16, 30, 6, 472, 71, 35, 250, 17, 3, 20);
INSERT INTO constituencies_constituency (id, name, `description`, hospitals, ambulances, death_hazards, schools, bookshops, libraries, fallout_shelters, railways, subway_stations, bus_routes, airports, bears, ladders, lighthouses, residential, officespace, cell_towers, power_stations, sewers, museums, galleries, parks, nuclear_plants, wind_farms, clocks, pigeons, farms, cows, rainfall, fighter_jets, tax_rate) VALUES (10, 'East Nussex', 'Bitter rivals of West Nussex.', 7, 5, 5, 7, 16, 4, 6, 6, 0, 2, 2, 24, 22, 4, 246, 29, 14, 6, 20, 12, 10, 10, 44, 18, 473, 167, 22, 177, 14, 4, 20);
INSERT INTO constituencies_constituency (id, name, `description`, hospitals, ambulances, death_hazards, schools, bookshops, libraries, fallout_shelters, railways, subway_stations, bus_routes, airports, bears, ladders, lighthouses, residential, officespace, cell_towers, power_stations, sewers, museums, galleries, parks, nuclear_plants, wind_farms, clocks, pigeons, farms, cows, rainfall, fighter_jets, tax_rate) VALUES (11, 'West Nussex', 'Bitter rivals of East Nussex.', 2, 13, 8, 16, 18, 5, 8, 5, 1, 11, 1, 32, 13, 7, 249, 32, 6, 8, 29, 3, 7, 14, 59, 19, 315, 241, 21, 153, 26, 3, 20);
INSERT INTO constituencies_constituency (id, name, `description`, hospitals, ambulances, death_hazards, schools, bookshops, libraries, fallout_shelters, railways, subway_stations, bus_routes, airports, bears, ladders, lighthouses, residential, officespace, cell_towers, power_stations, sewers, museums, galleries, parks, nuclear_plants, wind_farms, clocks, pigeons, farms, cows, rainfall, fighter_jets, tax_rate) VALUES (12, 'Here''s That City You Wanted', 'We''re just gonna put it here, so let''s us know if it needs moving.', 6, 7, 6, 12, 22, 8, 4, 3, 0, 8, 2, 16, 43, 12, 246, 26, 8, 4, 42, 20, 9, 2, 7, 15, 155, 84, 21, 158, 4, 2, 20);
INSERT INTO constituencies_constituency (id, name, `description`, hospitals, ambulances, death_hazards, schools, bookshops, libraries, fallout_shelters, railways, subway_stations, bus_routes, airports, bears, ladders, lighthouses, residential, officespace, cell_towers, power_stations, sewers, museums, galleries, parks, nuclear_plants, wind_farms, clocks, pigeons, farms, cows, rainfall, fighter_jets, tax_rate) VALUES (13, 'Isle of Blu', 'Isolated and boring as heck.', 2, 26, 3, 8, 19, 5, 5, 1, 0, 6, 4, 28, 37, 9, 217, 36, 10, 5, 38, 13, 4, 13, 55, 24, 208, 73, 24, 165, 26, 0, 20);
INSERT INTO constituencies_constituency (id, name, `description`, hospitals, ambulances, death_hazards, schools, bookshops, libraries, fallout_shelters, railways, subway_stations, bus_routes, airports, bears, ladders, lighthouses, residential, officespace, cell_towers, power_stations, sewers, museums, galleries, parks, nuclear_plants, wind_farms, clocks, pigeons, farms, cows, rainfall, fighter_jets, tax_rate) VALUES (14, 'Can''t', 'More like Won''t.', 2, 11, 4, 6, 15, 7, 10, 9, 5, 27, 24, 15, 53, 2, 224, 31, 10, 5, 33, 1, 7, 18, 63, 14, 104, 76, 25, 117, 7, 0, 20);
INSERT INTO constituencies_constituency (id, name, `description`, hospitals, ambulances, death_hazards, schools, bookshops, libraries, fallout_shelters, railways, subway_stations, bus_routes, airports, bears, ladders, lighthouses, residential, officespace, cell_towers, power_stations, sewers, museums, galleries, parks, nuclear_plants, wind_farms, clocks, pigeons, farms, cows, rainfall, fighter_jets, tax_rate) VALUES (15, 'Piggyton', 'Famous for its bacon sandwiches.', 13, 6, 2, 8, 8, 3, 7, 4, 1, 14, 5, 12, 5, 6, 231, 49, 14, 7, 27, 3, 2, 22, 37, 12, 134, 121, 31, 245, 15, 3, 20);
INSERT INTO constituencies_constituency (id, name, `description`, hospitals, ambulances, death_hazards, schools, bookshops, libraries, fallout_shelters, railways, subway_stations, bus_routes, airports, bears, ladders, lighthouses, residential, officespace, cell_towers, power_stations, sewers, museums, galleries, parks, nuclear_plants, wind_farms, clocks, pigeons, farms, cows, rainfall, fighter_jets, tax_rate) VALUES (16, 'Northplace', 'Not to be confused wtih Southplace.', 18, 12, 4, 15, 13, 6, 8, 2, 2, 13, 18, 16, 37, 7, 245, 71, 10, 9, 45, 5, 5, 12, 54, 29, 507, 80, 17, 130, 26, 3, 20);
INSERT INTO constituencies_constituency (id, name, `description`, hospitals, ambulances, death_hazards, schools, bookshops, libraries, fallout_shelters, railways, subway_stations, bus_routes, airports, bears, ladders, lighthouses, residential, officespace, cell_towers, power_stations, sewers, museums, galleries, parks, nuclear_plants, wind_farms, clocks, pigeons, farms, cows, rainfall, fighter_jets, tax_rate) VALUES (17, 'Southplace', 'Not to be confused with Northplace.', 6, 5, 5, 4, 15, 7, 7, 4, 0, 13, 3, 14, 47, 5, 236, 59, 5, 9, 37, 4, 6, 25, 15, 30, 247, 120, 19, 238, 12, 2, 20);
INSERT INTO constituencies_constituency (id, name, `description`, hospitals, ambulances, death_hazards, schools, bookshops, libraries, fallout_shelters, railways, subway_stations, bus_routes, airports, bears, ladders, lighthouses, residential, officespace, cell_towers, power_stations, sewers, museums, galleries, parks, nuclear_plants, wind_farms, clocks, pigeons, farms, cows, rainfall, fighter_jets, tax_rate) VALUES (18, 'New York', 'The newer york.', 3, 7, 15, 17, 21, 6, 2, 3, 0, 14, 2, 16, 27, 6, 239, 32, 11, 8, 31, 12, 3, 20, 35, 10, 80, 216, 24, 220, 53, 3, 20);
INSERT INTO constituencies_constituency (id, name, `description`, hospitals, ambulances, death_hazards, schools, bookshops, libraries, fallout_shelters, railways, subway_stations, bus_routes, airports, bears, ladders, lighthouses, residential, officespace, cell_towers, power_stations, sewers, museums, galleries, parks, nuclear_plants, wind_farms, clocks, pigeons, farms, cows, rainfall, fighter_jets, tax_rate) VALUES (19, 'Dictionaryshire', 'Created the first dictionary. It contained 2 words in its first edition, but got to 5 in its reprint.', 7, 8, 1, 19, 16, 4, 11, 5, 0, 17, 4, 18, 30, 3, 231, 56, 10, 6, 34, 7, 3, 31, 43, 19, 266, 148, 30, 236, 36, 3, 20);
INSERT INTO constituencies_constituency (id, name, `description`, hospitals, ambulances, death_hazards, schools, bookshops, libraries, fallout_shelters, railways, subway_stations, bus_routes, airports, bears, ladders, lighthouses, residential, officespace, cell_towers, power_stations, sewers, museums, galleries, parks, nuclear_plants, wind_farms, clocks, pigeons, farms, cows, rainfall, fighter_jets, tax_rate) VALUES (20, 'Wear and Tear', 'Fashionistas haven and deathplace.', 7, 7, 5, 3, 12, 7, 12, 7, 1, 14, 3, 20, 28, 11, 229, 35, 1, 10, 43, 8, 5, 30, 49, 27, 282, 38, 27, 160, 30, 5, 20);
INSERT INTO constituencies_constituency (id, name, `description`, hospitals, ambulances, death_hazards, schools, bookshops, libraries, fallout_shelters, railways, subway_stations, bus_routes, airports, bears, ladders, lighthouses, residential, officespace, cell_towers, power_stations, sewers, museums, galleries, parks, nuclear_plants, wind_farms, clocks, pigeons, farms, cows, rainfall, fighter_jets, tax_rate) VALUES (21, 'Wilting Flowers', 'Rolling fields and a bitter sun.', 9, 8, 5, 10, 21, 9, 18, 2, 16, 16, 4, 27, 24, 1, 256, 59, 13, 11, 14, 9, 6, 31, 14, 11, 323, 175, 20, 144, 6, 1, 20);
INSERT INTO constituencies_constituency (id, name, `description`, hospitals, ambulances, death_hazards, schools, bookshops, libraries, fallout_shelters, railways, subway_stations, bus_routes, airports, bears, ladders, lighthouses, residential, officespace, cell_towers, power_stations, sewers, museums, galleries, parks, nuclear_plants, wind_farms, clocks, pigeons, farms, cows, rainfall, fighter_jets, tax_rate) VALUES (22, 'Shire', 'They got tired of people trying to pronounce it.', 10, 11, 5, 9, 12, 9, 12, 5, 1, 20, 2, 26, 28, 10, 268, 30, 10, 13, 30, 17, 0, 29, 20, 27, 102, 230, 23, 173, 52, 1, 20);
INSERT INTO constituencies_constituency (id, name, `description`, hospitals, ambulances, death_hazards, schools, bookshops, libraries, fallout_shelters, railways, subway_stations, bus_routes, airports, bears, ladders, lighthouses, residential, officespace, cell_towers, power_stations, sewers, museums, galleries, parks, nuclear_plants, wind_farms, clocks, pigeons, farms, cows, rainfall, fighter_jets, tax_rate) VALUES (23, 'Mudland', 'Watch your step!', 3, 6, 4, 9, 7, 5, 6, 4, 0, 17, 6, 28, 23, 7, 248, 67, 10, 13, 13, 8, 6, 10, 46, 3, 213, 6, 25, 209, 26, 0, 20);
INSERT INTO constituencies_constituency (id, name, `description`, hospitals, ambulances, death_hazards, schools, bookshops, libraries, fallout_shelters, railways, subway_stations, bus_routes, airports, bears, ladders, lighthouses, residential, officespace, cell_towers, power_stations, sewers, museums, galleries, parks, nuclear_plants, wind_farms, clocks, pigeons, farms, cows, rainfall, fighter_jets, tax_rate) VALUES (24, 'Hurry', 'Fast paced when it comes to technology! You best run as the public transport system is a little busy, especially in work hours! Hurry is seen as the hub of fast choices and new invention, all in the name of making things faster. After all, it was Hurry who first initiated bears into the police force and all constituencies have followed since! Truly remarkable and wholly inventive.', 4, 4, 3, 8, 14, 5, 3, 3, 0, 7, 3, 24, 46, 3, 245, 46, 11, 6, 18, 9, 8, 11, 16, 23, 397, 200, 28, 240, 26, 3, 20);

-- changeset Stanley:02010503 labels:v2.1.0
CREATE TABLE constituencies_costs (attribute VARCHAR(256) NOT NULL, cost INT NULL, CONSTRAINT PK_CONSTITUENCIES_COSTS PRIMARY KEY (attribute), UNIQUE (attribute));

-- changeset Stanley:02010504 labels:v2.1.0
INSERT INTO constituencies_costs (attribute, cost) VALUES ('airports', 100);
INSERT INTO constituencies_costs (attribute, cost) VALUES ('ambulances', 15);
INSERT INTO constituencies_costs (attribute, cost) VALUES ('bears', 20);
INSERT INTO constituencies_costs (attribute, cost) VALUES ('bookshops', -50);
INSERT INTO constituencies_costs (attribute, cost) VALUES ('bus_routes', 30);
INSERT INTO constituencies_costs (attribute, cost) VALUES ('cell_towers', 30);
INSERT INTO constituencies_costs (attribute, cost) VALUES ('clocks', 1);
INSERT INTO constituencies_costs (attribute, cost) VALUES ('cows', 1);
INSERT INTO constituencies_costs (attribute, cost) VALUES ('death_hazards', -150);
INSERT INTO constituencies_costs (attribute, cost) VALUES ('fallout_shelters', 250);
INSERT INTO constituencies_costs (attribute, cost) VALUES ('farms', -20);
INSERT INTO constituencies_costs (attribute, cost) VALUES ('fighter_jets', 500);
INSERT INTO constituencies_costs (attribute, cost) VALUES ('galleries', 15);
INSERT INTO constituencies_costs (attribute, cost) VALUES ('hospitals', 200);
INSERT INTO constituencies_costs (attribute, cost) VALUES ('ladders', 5);
INSERT INTO constituencies_costs (attribute, cost) VALUES ('libraries', 100);
INSERT INTO constituencies_costs (attribute, cost) VALUES ('lighthouses', 30);
INSERT INTO constituencies_costs (attribute, cost) VALUES ('museums', 25);
INSERT INTO constituencies_costs (attribute, cost) VALUES ('nuclear_plants', 125);
INSERT INTO constituencies_costs (attribute, cost) VALUES ('officespace', 100);
INSERT INTO constituencies_costs (attribute, cost) VALUES ('parks', 10);
INSERT INTO constituencies_costs (attribute, cost) VALUES ('pigeons', -1);
INSERT INTO constituencies_costs (attribute, cost) VALUES ('power_stations', 35);
INSERT INTO constituencies_costs (attribute, cost) VALUES ('railways', 70);
INSERT INTO constituencies_costs (attribute, cost) VALUES ('rainfall', 0);
INSERT INTO constituencies_costs (attribute, cost) VALUES ('residential', 50);
INSERT INTO constituencies_costs (attribute, cost) VALUES ('schools', 125);
INSERT INTO constituencies_costs (attribute, cost) VALUES ('sewers', 50);
INSERT INTO constituencies_costs (attribute, cost) VALUES ('subway_stations', 50);
INSERT INTO constituencies_costs (attribute, cost) VALUES ('wind_farms', 50);

-- changeset Stanley:02010505 labels:v2.1.0
CREATE TABLE monuments_monument (id INT AUTO_INCREMENT NOT NULL, constituency_id INT NOT NULL, name VARCHAR(256) NULL, `description` MEDIUMTEXT NULL, CONSTRAINT PK_MONUMENTS_MONUMENT PRIMARY KEY (id), UNIQUE (id));

-- changeset Stanley:02010506 labels:v2.1.0
CREATE INDEX monument_constituency_idx ON monuments_monument(constituency_id);

-- changeset Stanley:02010507 labels:v2.1.0
ALTER TABLE monuments_monument ADD CONSTRAINT monument_constituency FOREIGN KEY (constituency_id) REFERENCES constituencies_constituency (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
